name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  Server-Agent:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019] #, windows-2016]
    steps:
      - uses: actions/checkout@v2
      - name: PSVersion Table
        run: $psversiontable
      - name: Install
        run: |
          $ErrorActionPreference = "Stop"
          & .\extras\install.ps1 -Verbose
          if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      - name: "Install Bolt"
        run: |
          choco install puppet-bolt --yes --no-progress
          Import-Module C:\ProgramData\chocolatey\helpers\chocolateyProfile.psm1
          Update-SessionEnvironment
          Import-Module PuppetBolt
      - name: "Install Bundler"
        run: |
          gem install bundler
          bundle install --gemfile ./spec/Gemfile
      - name: "Provision Test"
        run: |
          bundle exec rake 'litmus:provision[provision::provision_service, centos-7]' --gemfile ./spec/Gemfile
          echo ::group::=== INVENTORY ===
          type ./spec/fixtures/litmus_inventory.yml
          echo ::endgroup::